services:
  - type: web
    name: my-express-api
    env: node
    region: singapore  # Hoặc chọn khu vực gần Việt Nam nhất
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    plan: free

    envVars:
      - key: NODE_ENV
        value: production

      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome-stable"

      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
